theme = "flatwhite"

[editor]
bufferline = "multiple"
color-modes = true
cursorline = true
line-number = "absolute"
mouse = true
true-color = true

[editor.indent-guides]
render = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "file-name", "total-line-numbers"]
center = []
right = ["diagnostics", "file-encoding", "file-line-ending", "file-type", "position-percentage", "position"]
separator = "│"

[editor.statusline.mode]
normal = "NORMAL"
insert = "INSERT"
select = "SELECT"

[editor.file-picker]
hidden = false

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⤶"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[keys.normal]
"esc" = ["collapse_selection", "keep_primary_selection"]
"C-d" = ["half_page_down", "align_view_center"]
"X" = "extend_line_above"


[keys.normal.space]
space = "file_picker"
w = ":w"
q = ":q"

[keys.normal.space.c]
r = ":config-reload"
o = ":config-open"
w = ":set whitespace.render all"
W = ":set whitespace.render none"

[keys.insert]
C-l = "normal_mode"
C-r = "redo"
C-s = [ "normal_mode", ":w" ]
C-u = "undo"
C-z = "undo"
