theme = "flatwhite"

[editor]
bufferline = "multiple"
color-modes = true
cursorline = true
line-number = "absolute"
mouse = true
true-color = true
completion-trigger-len = 1
auto-completion = true

[editor.indent-guides]
render = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "separator", "file-name", "spinner"]
center = ["version-control"]
right = [
  "diagnostics",
  "separator",
  "selections",
  "separator",
  "file-type",
  "separator",
  "position",
]
separator = "│"

[editor.statusline.mode]
normal = "N"
insert = "I"
select = "S"

[editor.file-picker]
hidden = false

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⤶"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[keys.normal]
"esc" = ["collapse_selection", "keep_primary_selection"]
"C-d" = ["half_page_down", "align_view_center"]
"X" = "extend_line_above"
"tab" = ":bn"
"S-tab" = ":bp"

[keys.normal.backspace]
f = ":fmt"

[keys.normal.space]
space = "file_picker"
n = ":new"
w = ":w"
q = ":q"
x = ":buffer-close"

[keys.normal.space.c]
r = ":config-reload"
o = ":config-open"
w = ":set whitespace.render all"
W = ":set whitespace.render none"
