theme = "base16_transparent"
# icons = "nerdfonts"

[editor]
color-modes = true
cursorline = true
mouse = true
true-color = true
auto-pairs = false
auto-completion = true
line-number = "absolute"
completion-trigger-len = 1
idle-timeout = 50

[editor.indent-guides]
render = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["file-name", "spinner"]
center = ["version-control"]
right = [
  "diagnostics",
  "selections",
  "file-type",
  "position",
  "total-line-numbers",
]

[editor.soft-wrap]
enable = true

[editor.statusline.mode]
normal = "N"
insert = "I"
select = "S"

[editor.file-picker]
hidden = false

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⤶"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[keys.normal]
"esc" = ["collapse_selection", "keep_primary_selection"]
"C-d" = ["half_page_down", "align_view_center"]
"X" = "extend_line_above"
"tab" = ":bn"
"S-tab" = ":bp"
"C-A-j" = [
  'ensure_selections_forward',
  'extend_to_line_bounds',
  'extend_char_right',
  'extend_char_left',
  'delete_selection',
  'add_newline_below',
  'move_line_down',
  'replace_with_yanked',
]
"C-A-k" = [
  'ensure_selections_forward',
  'extend_to_line_bounds',
  'extend_char_right',
  'extend_char_left',
  'delete_selection',
  'move_line_up',
  'add_newline_above',
  'move_line_up',
  'replace_with_yanked',
]

[keys.normal.space]
space = "file_picker"
e = ":sh helix-exec helix-nnn-open"
i = ":sh helix-exec helix-filename-to-clipboard"
n = ":new"
q = ":q"
w = ":w"
x = ":buffer-close"

[keys.normal.space.c]
r = ":config-reload"
e = ":config-open"
w = ":set whitespace.render all"
W = ":set whitespace.render none"
i = ":set lsp.display-inlay-hints true"
I = ":set lsp.display-inlay-hints false"
l = ":set line-number absolute"
L = ":set line-number relative"
