[[language]]
name = "rust"
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[language]]
name = "toml"
indent = { tab-width = 2, unit = "  " }
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true

[[language]]
name = "markdown"
auto-format = true
language-servers = ["marksman"]
formatter = { command = "prettier", args = ["--parser", "markdown"] }

[[language]]
name = "css"
language-servers = [
  { except-features = [
    "format",
  ], name = "vscode-css-language-server" },
]
formatter = { command = "prettier", args = ["--parser", "css"] }

[[language]]
name = "scss"
language-servers = [
  { except-features = [
    "format",
  ], name = "vscode-css-language-server" },
]
formatter = { command = "prettier", args = ["--parser", "scss"] }

[[language]]
name = "html"
language-servers = [
  { except-features = [
    "format",
  ], name = "vscode-html-language-server" },
]
formatter = { command = "prettier", args = ["--parser", "html"] }
auto-format = true

[[language]]
name = "yaml"
language-servers = [
  { except-features = [
    "format",
  ], name = "yaml-language-server" },
]
formatter = { command = "prettier", args = ["--parser", "yaml"] }
auto-format = true

[[language]]
name = "javascript"
language-servers = [
  { except-features = [
    "format",
  ], name = "typescript-language-server" },
  { name = "eslint" },
]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "jsx"
language-servers = [
  { except-features = [
    "format",
  ], name = "typescript-language-server" },
  { name = "eslint" },
]
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
language-servers = [
  { except-features = [
    "format",
  ], name = "typescript-language-server" },
  { name = "eslint" },
]
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
language-servers = [
  { except-features = [
    "format",
  ], name = "typescript-language-server" },
  { name = "eslint" },
]
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[language-server.typescript-language-server]
args = ["--stdio"]
command = "typescript-language-server"

[language-server.typescript-language-server.config]
documentFormatting = false

[language-server.eslint]
args = ["--stdio"]
command = "vscode-eslint-language-server"

[language-server.eslint.config]
nodePath = ""
validate = "on"
run = "onType"
rulesCustomizations = []
experimental = { useFlatConfig = false }
problems = { shortenToSingleLine = false }
format = true

[language-server.eslint.config.codeAction]
[language-server.eslint.config.codeAction.disableRuleComment]
enable = true
location = "separateLine"

[language-server.eslint.config.codeAction.showDocumentation]
enable = true

[language-server.eslint.config.codeActionOnSave]
enable = true
mode = "all"
