colors:
  bright:
    black: '#605a52'
    blue: '#7382a0'
    cyan: '#7ecbc8'
    green: '#afcb85'
    magenta: '#a390f0'
    red: '#cc7c8a'
    white: '#d6d6dd'
    yellow: '#ebc88d'
  cursor:
    cursor: '#535353'
    text: '#f7f3ee'
  normal:
    black: '#605a52'
    blue: '#7382a0'
    cyan: '#7ecbc8'
    green: '#afcb85'
    magenta: '#a390f0'
    red: '#cc7c8a'
    white: '#d6d6dd'
    yellow: '#ebc88d'
  primary:
    background: '#181818'
    foreground: '#d6d6dd'
  selection:
    background: '#1f3661'
    text: '#d6d6dd'
cursor:
  blink_interval: 750
  style:
    blinking: Always
    shape: Beam
  thickness: 0.3
  unfocused_hollow: false
  vi_mode_style:
    shape: Beam
draw_bold_text_with_bright_colors: true
env:
  TERM: xterm-256color
font:
  bold:
    family: Liga SFMono Nerd Font
    style: Regular
  bold_italic:
    family: Liga SFMono Nerd Font
    style: Regular Italic
  builtin_box_drawing: true
  italic:
    family: Liga SFMono Nerd Font
    style: Italic
  normal:
    family: Liga SFMono Nerd Font
    style: Regular
  offset:
    x: 0
    y: 0
  size: 14.5
mouse:
  hide_when_typing: false
scrolling:
  history: 100000
  multiplier: 6
selection:
  save_to_clipboard: true
  semantic_escape_chars: ",â”‚`|:\"' ()[]{}<>\t"
shell:
  program: /bin/zsh
window:
  decorations: buttonless
  opacity: 1.0
  padding:
    x: 16
    y: 16
