colors:
  bright:
    black: '#605a52'
    blue: '#7382a0'
    cyan: '#588C7C'
    green: '#81895d'
    magenta: '#9c739c'
    red: '#ff1414'
    white: '#e4ddd2'
    yellow: '#f2a60d'
  cursor:
    cursor: '#605a52'
    text: '#f7f3ee'
  normal:
    black: '#605a52'
    blue: '#7382a0'
    cyan: '#588C7C'
    green: '#81895d'
    magenta: '#9c739c'
    red: '#ff1414'
    white: '#e4ddd2'
    yellow: '#f2a60d'
  primary:
    background: '#f7f3ee'
    foreground: '#605a52'
  selection:
    background: '0x6a4cff'
    text: '0xe4ddd2'
cursor:
  blink_interval: 750
  style:
    blinking: Always
    shape: Beam
  thickness: 0.3
  unfocused_hollow: false
  vi_mode_style:
    shape: Beam
draw_bold_text_with_bright_colors: true
env:
  TERM: xterm-256color
font:
  bold:
    family: Liga SFMono Nerd Font
    style: Regular
  bold_italic:
    family: Liga SFMono Nerd Font
    style: Regular Italic
  builtin_box_drawing: true
  italic:
    family: Liga SFMono Nerd Font
    style: Italic
  normal:
    family: Liga SFMono Nerd Font
    style: Regular
  offset:
    x: 0
    y: 0
  size: 14.5
mouse:
  hide_when_typing: false
scrolling:
  history: 100000
  multiplier: 6
selection:
  save_to_clipboard: true
  semantic_escape_chars: ",â”‚`|:\"' ()[]{}<>\t"
shell:
  program: /bin/zsh
window:
  decorations: Buttonless
  opacity: 1.0
  padding:
    x: 16
    y: 16
