colors:
  bright:
    black: '#879193'
    blue: '#97B8DE'
    cyan: '#5096AB'
    green: '#72CCBA'
    magenta: '#8C629C'
    red: '#E36D5B'
    white: '#EFEFF1'
    yellow: '#F2C866'
  normal:
    black: '#4B5254'
    blue: '#91B9C7'
    cyan: '#4D9391'
    green: '#6FB593'
    magenta: '#845A84'
    red: '#CD5C60'
    white: '#E4E4E8'
    yellow: '#DBAC66'
  primary:
    background: '#18181B'
    foreground: '#E4E4E8'
cursor:
  blink_interval: 750
  style:
    blinking: Always
    shape: Beam
  thickness: 0.3
  unfocused_hollow: false
  vi_mode_style:
    shape: Beam
draw_bold_text_with_bright_colors: true
env:
  TERM: xterm-256color
font:
  bold:
    family: MonoLisa Nerd Font
    style: Regular
  bold_italic:
    family: MonoLisa Nerd Font
    style: Bold Italic
  italic:
    family: MonoLisa Nerd Font
    style: Italic
  normal:
    family: MonoLisa Nerd Font
    style: Regular
  size: 14
hints:
  alphabet: jfkdls;ahgurieowpq
  enabled:
  - command: open
    hyperlinks: true
    mouse:
      enabled: true
      mods: None
    post_processing: true
    regex: "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\0-\x1F\x7F-\x9F<>\"\\s{-}\\^⟨⟩`]+"
key_bindings:
- action: ToggleSimpleFullscreen
  key: F2
live_config_reload: true
mouse:
  hide_when_typing: false
scrolling:
  history: 100000
  multiplier: 6
selection:
  save_to_clipboard: true
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
shell:
  program: /bin/zsh
window:
  decorations: buttonless
  opacity: 1
  option_as_alt: OnlyLeft
  padding:
    x: 16
    y: 16
