env:
  TERM: xterm-256color

window:
  decorations: Buttonless
  opacity: 1
  padding:
    x: 30
    y: 30

scrolling:
  history: 100000
  multiplier: 6

font:
  size: 14.5
  normal:
    family: Liga SFMono Nerd Font
    style: Regular
  bold:
    family: Liga SFMono Nerd Font
    style: Regular
  italic:
    family: Liga SFMono Nerd Font
    style: Italic
  bold_italic:
    family: Liga SFMono Nerd Font
    style: Regular Italic
  builtin_box_drawing: true
  offset:
    x: 0
    y: 0

draw_bold_text_with_bright_colors: true

selection:
  semantic_escape_chars: ",â”‚`|:\"' ()[]{}<>\t"
  save_to_clipboard: true

cursor:
  style:
    shape: Beam
    blinking: Always
  unfocused_hollow: false
  thickness: 0.3
  blink_interval: 750
  vi_mode_style:
    shape: Beam

shell:
  program: /bin/zsh

colors:
  # Default colors
  primary:
    background: "#161616"
    foreground: "0xa9b1d6"

  # Normal colors
  normal:
    black: "0x32344a"
    red: "0xf7768e"
    green: "0x9ece6a"
    yellow: "0xe0af68"
    blue: "0x7aa2f7"
    magenta: "0xad8ee6"
    cyan: "0x449dab"
    white: "0x787c99"

  # Bright colors
  bright:
    black: "0x444b6a"
    red: "0xff7a93"
    green: "0xb9f27c"
    yellow: "0xff9e64"
    blue: "0x7da6ff"
    magenta: "0xbb9af7"
    cyan: "0x0db9d7"
    white: "0xacb0d0"

mouse:
  hide_when_typing: true
