font:
  normal:
    family: FiraCode Nerd Font
  bold:
    family: Fira Code Bold Nerd Font Complete
  italic:
    family: Victor Mono Medium Italic Nerd Font Complete
    style: Italic
  bold_italic:
    family: Victor Mono Bold Italic Nerd Font Complete
  size: 14.5
