font:
  normal:
    family: Iosevka Nerd Font Mono
    style: Regular
  bold:
    family: Iosevka Nerd Font Mono
    style: Bold
  italic:
    family: Iosevka NF
    style: Italic
  bold_italic:
    family: Iosevka NF
    style: Bold Italic
  size: 14
  glyph_offset:
    x: 0
    y: 0
