font:
  normal:
    family: JetBrainsMono Nerd Font Mono
    style: Regular
  bold:
    family: JetBrainsMono Nerd Font Mono
    style: Bold
  italic:
    family: JetBrainsMono Nerd Font Mono
    style: Italic
  size: 14.5
  offset:
    x: 0
    y: -2
  glyph_offset:
    x: 0
    y: 0
