font:
  normal:
    family: MonoLisa Nerd Font
    style: Regular
  bold:
    family: MonoLisa Nerd Font
    style: Regular
  italic:
    family: MonoLisa Nerd Font
    style: Italic
  bold_italic:
    family: MonoLisa Nerd Font
    style: Bold Italic
  size: 14
