shell = "zsh"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.alias-tips]
github = "djui/alias-tips"

[plugins.oh-my-zsh]
github = "ohmyzsh/ohmyzsh"
use = [
    "lib/completion.zsh",
    "lib/clipboard.zsh",
    "lib/git.zsh",
    "lib/directories.zsh",
    "plugins/git/git.plugin.zsh",
    "plugins/colored-man-pages/colored-man-pages.plugin.zsh",
    ]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-better-npm-completion]
github = "lukechilds/zsh-better-npm-completion"

[plugins.starship]
inline = 'eval "$(starship init zsh)"'
