colors:
  primary:
    background: "#121212"
    foreground: "#afafaf"
  normal:
    black: "#000000"
    red: "#fd6389"
    green: "#2cdce7"
    yellow: "#d7af87"
    blue: "#84afd7"
    magenta: "#fd6389"
    cyan: "#7cdce7"
    white: "#ffffff"
  bright:
    black: "#3a3b3f"
    red: "#fd6389"
    green: "#2cdce7"
    yellow: "#928374"
    blue: "#84afd7"
    magenta: "#fd6389"
    cyan: "#7cdce7"
    white: "#eeeeee"
