"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
ratio = [0, 1, 0]
linemode = "size"
sort_by = "natural"
sort_dir_first = true
show_hidden = true

[opener]
edit = [{ run = 'hx-open.sh "$@"', block = true }]
