[colors]
background = '#2b292d'
foreground = '#fecdb2'

cursor_bg = '#fecdb2'
cursor_fg = '#383539'
cursor_border = '#fecdb2'

selection_bg = '#4d424b'
selection_fg = '#fecdb2'

ansi = [
  '#1f1e20',
  '#c05862',
  '#b1b695',
  '#f5d76e',
  '#ffa07a',
  '#f6b6c9',
  '#bfbfcf',
  '#f5f5f5',
]
brights = [
  '#2b292d',
  '#e06b75',
  '#9f9f7c',
  '#fff27a',
  '#e88c6f',
  '#ffb9cc',
  '#d1d1e0',
  '#ffffff',
]
